#!/bin/bash

#should I do this on startvnc?
#vglclient &

XFCE_PANEL_MIGRATE_DEFAULT=true startxfce4 &

#not sure where this needs to be.. but maybe doesn't matter? without this, fsleyes popups
export FSLDIR=/

#vglrun fsleyes `find $INPUT_DIR -name *.nii.gz` &
brainstorm &
pid=$!

#maximize fsleyes
sleep 5
id=`wmctrl -pl | grep " $pid " | cut -f 1 -d " "`
echo $id > /id.txt
wmctrl -i -r $id -b add,fullscreen

sleep 3600
